# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9aa7b58a8951b01a63705620337d7ba3bcbff0959e482a11b445b890918e91b5d619a5bf09c79506312341d12a64b39af9ac19ad1e45aa830929b13b92106b68

test:
  secret_key_base: da5c0ad00fcc86947ad90ef6cb6ffe4494c8bc72a634c432f40a42469ee76f0f518fddbe571656bcc7450a8f672555cb6b282e8dd221e3a8d4ddaa400fe19828

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
